<?php

declare(strict_types=1);
// Runs against a uniquely named disposable database, never the application database.
date_default_timezone_set('Asia/Kolkata');
require dirname(__DIR__) . '/database/install.php';
require_once dirname(__DIR__) . '/includes/excel-export.php';
$config = require dirname(__DIR__) . '/config.php';
$database = 'bhavi_portal_test_' . bin2hex(random_bytes(6));
$pdo = new PDO("mysql:host={$config['db_host']};port={$config['db_port']};charset=utf8mb4", $config['db_user'], $config['db_password'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
$pdo->exec("SET time_zone='+05:30'");
$process = null;
$temporary = [];
$checks = 0;
function expect(bool $condition, string $label): void
{
    global $checks;
    if (!$condition) throw new RuntimeException($label);
    $checks++;
}
function scalar(string $sql, array $params = []): mixed
{
    global $pdo;
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    return $stmt->fetchColumn();
}
final class Browser
{
    public string $csrf = '';
    private string $cookie;
    public function __construct(private string $base)
    {
        global $temporary;
        $this->cookie = tempnam(sys_get_temp_dir(), 'bhavi_cookie_');
        $temporary[] = $this->cookie;
    }
    public function request(string $path, ?array $data = null): array
    {
        $handle = curl_init($this->base . '/' . $path);
        $headers = [];
        curl_setopt_array($handle, [CURLOPT_RETURNTRANSFER => true, CURLOPT_COOKIEFILE => $this->cookie, CURLOPT_COOKIEJAR => $this->cookie, CURLOPT_CONNECTTIMEOUT => 2, CURLOPT_TIMEOUT => 600, CURLOPT_HEADERFUNCTION => static function ($handle, $line) use (&$headers) {
            $parts = explode(':', $line, 2);
            if (count($parts) === 2) $headers[strtolower(trim($parts[0]))] = trim($parts[1]);
            return strlen($line);
        }]);
        if ($data !== null) {
            curl_setopt($handle, CURLOPT_POST, true);
            curl_setopt($handle, CURLOPT_POSTFIELDS, array_filter($data, static fn($v) => $v instanceof CURLFile) ? $data : http_build_query($data));
        }
        $body = curl_exec($handle);
        if ($body === false) throw new RuntimeException(curl_error($handle));
        $status = curl_getinfo($handle, CURLINFO_RESPONSE_CODE);
        unset($handle);
        if (preg_match('/name="csrf" value="([a-f0-9]{64})"/', $body, $match)) $this->csrf = $match[1];
        if ($status >= 500 || str_contains($body, 'Fatal error') || str_contains($body, 'Warning:')) throw new RuntimeException($path . ' returned ' . $status . ': ' . substr(strip_tags($body), 0, 400));
        return ['status' => $status, 'headers' => $headers, 'body' => $body];
    }
    public function post(string $path, array $data): array
    {
        return $this->request($path, array_merge(['csrf' => $this->csrf], $data));
    }
    public function login(string $username, string $password, string $dashboard): void
    {
        $this->request('login.php');
        $response = $this->post('authenticate.php', ['username' => $username, 'password' => $password]);
        expect($response['status'] === 303 && $response['headers']['location'] === $dashboard, 'Login redirect for ' . $username);
        expect($this->request($dashboard)['status'] === 200, 'Dashboard renders for ' . $username);
    }
}
try {
    portal_install($pdo, $database);
    portal_install($pdo, $database);
    expect((int)scalar('SELECT COUNT(*) FROM departments') === 5, 'Idempotent schema installation');
    $socket = stream_socket_server('tcp://127.0.0.1:0', $errno, $error);
    if (!$socket) throw new RuntimeException($error);
    $address = stream_socket_get_name($socket, false);
    fclose($socket);
    $log = tempnam(sys_get_temp_dir(), 'bhavi_server_');
    $temporary[] = $log;
    $environment = getenv();
    $environment['BHAVI_DB_NAME'] = $database;
    $process = proc_open([PHP_BINARY, '-d', 'session.save_path=' . sys_get_temp_dir(), '-d', 'upload_max_filesize=100M', '-d', 'post_max_size=2100M', '-d', 'max_file_uploads=21', '-S', $address, '-t', dirname(__DIR__)], [0 => ['pipe', 'r'], 1 => ['file', $log, 'a'], 2 => ['file', $log, 'a']], $pipes, dirname(__DIR__), $environment);
    if (!is_resource($process)) throw new RuntimeException('Unable to start the test server.');
    fclose($pipes[0]);
    $ready = false;
    for ($i = 0; $i < 50; $i++) {
        $connection = @stream_socket_client('tcp://' . $address, $errno, $error, 0.1);
        if ($connection) {
            fclose($connection);
            $ready = true;
            break;
        }
        usleep(100000);
    }
    if (!$ready) throw new RuntimeException('Test server did not start: ' . file_get_contents($log));
    $base = 'http://' . $address;
    $guest = new Browser($base);
    expect($guest->request('index.php')['headers']['location'] === 'setup.php', 'Fresh installation opens setup');
    $guest->request('setup.php');
    $password = 'Integration-Test-2026!';
    expect($guest->post('setup.php', ['admin_name' => 'Test Administrator', 'admin_username' => 'admin.test', 'admin_password' => $password, 'manager_name' => 'Test Manager', 'manager_username' => 'manager.test', 'manager_password' => $password])['status'] === 303, 'Initial account creation');
    expect((int)scalar('SELECT COUNT(*) FROM users') === 2, 'Setup creates exactly two accounts');
    expect($guest->request('setup.php')['headers']['location'] === 'login.php', 'Setup closes after accounts exist');
    $routes = ['admin-dashboard.php', 'manager-dashboard.php', 'admin-employees.php', 'add-client.php', 'admin-holidays.php', 'manager-holidays.php', 'apply-leaves.php', 'check-leave.php', 'manager-dailywork.php', 'manager-leave-requist.php', 'manager-notification.php', 'employee-brands-assets.php', 'client-reuirement.php', 'website-employee-dashboard.php', 'seo-employee-dashboard.php', 'design-employee-dashboard.php', 'socialmedia-employee-dashboard.php', 'telecaller-employee-dashboard.php', 'manager-assign-work.php', 'manager-review-work.php', 'download-work.php', 'download-asset.php'];
    foreach ($routes as $route) expect($guest->request($route)['headers']['location'] === 'login.php', 'Unauthenticated route ' . $route);
    $guest->request('login.php');
    expect($guest->post('authenticate.php', ['username' => 'admin.test', 'password' => 'bad-password'])['headers']['location'] === 'login.php', 'Bad password rejected');
    expect(str_contains($guest->request('login.php')['body'], 'Incorrect username or password'), 'Login error appears only after failure');
    expect(!str_contains($guest->request('login.php')['body'], 'Incorrect username or password'), 'Login error clears');
    $admin = new Browser($base);
    $admin->login('admin.test', $password, 'admin-dashboard.php');
    $manager = new Browser($base);
    $manager->login('manager.test', $password, 'manager-dashboard.php');
    expect($admin->request('manager-dashboard.php')['status'] === 403, 'Admin dashboard role separation');
    expect($manager->request('admin-dashboard.php')['status'] === 403, 'Manager cannot open admin dashboard');
    expect($manager->request('admin-add-employee.php')['status'] === 403, 'Manager cannot create users');
    expect($admin->request('admin-add-employee.php', ['csrf' => 'invalid'])['status'] === 419, 'CSRF rejected');
    $employeeIds = [];
    $browsers = [];
    $dashboards = ['website' => 'website-employee-dashboard.php', 'seo' => 'seo-employee-dashboard.php', 'design_video' => 'design-employee-dashboard.php', 'telecaller' => 'telecaller-employee-dashboard.php', 'social_media' => 'socialmedia-employee-dashboard.php'];
    foreach ($dashboards as $code => $dashboard) {
        $admin->request('admin-add-employee.php');
        $response = $admin->post('admin-add-employee.php', ['employee_name' => 'Employee ' . $code, 'email' => $code . '@example.test', 'username' => $code . '.test', 'temporary_password' => $password, 'role' => 'employee', 'account_status' => 'active', 'department_id' => scalar('SELECT id FROM departments WHERE code=?', [$code]), 'designation' => 'Team member', 'joining_date' => date('Y-m-d'), 'manager_id' => '']);
        expect($response['status'] === 303, 'Create ' . $code . ' employee');
        $employeeIds[$code] = (int)scalar('SELECT id FROM users WHERE username=?', [$code . '.test']);
        expect(password_verify($password, (string)scalar('SELECT password_hash FROM users WHERE id=?', [$employeeIds[$code]])), 'Password stored as hash');
        $browsers[$code] = new Browser($base);
        $browsers[$code]->login($code . '.test', $password, $dashboard);
        expect($browsers[$code]->request('admin-dashboard.php')['status'] === 403, 'Employee forbidden admin dashboard');
        expect($browsers[$code]->request('manager-dailywork.php')['status'] === 403, 'Employee forbidden team reports');
        expect($browsers[$code]->request('download-work.php')['status'] === 403, 'Employee forbidden team export');
    }
    $attendanceEmployee=$browsers['website'];
    expect(str_contains($attendanceEmployee->request($dashboards['website'])['body'],'attendance.php'), 'Employee sidebar has attendance login control');
    expect(str_contains($admin->request('admin-dashboard.php')['body'],'href="employee-attendance.php"'), 'Admin sidebar links to employee attendance');
    expect($manager->request('employee-attendance.php')['status']===403, 'Manager cannot access admin attendance list');
    expect($attendanceEmployee->request('employee-attendance.php?employee='.$employeeIds['seo'])['status']===403, 'Employee cannot view another employee attendance');
    expect($admin->post('attendance.php',['action'=>'login'])['status']===403, 'Staff cannot submit employee attendance controls');
    expect($attendanceEmployee->post('attendance.php',['action'=>'login'])['status']===303, 'Employee attendance login saves');
    $attendanceId=(int)scalar('SELECT id FROM employee_attendance_sessions WHERE employee_id=? AND logout_at IS NULL',[$employeeIds['website']]);
    expect($attendanceId>0 && scalar('SELECT login_at FROM employee_attendance_sessions WHERE id=?',[$attendanceId])!==null, 'Attendance login timestamp persists');
    expect(str_contains($attendanceEmployee->request($dashboards['website'])['body'],'name="action" value="logout"'), 'Active attendance shows logout control');
    expect($attendanceEmployee->post('attendance.php',['action'=>'login'])['status']===409, 'Duplicate attendance login rejected');
    expect($attendanceEmployee->post('attendance.php',['action'=>'logout'])['status']===303, 'Employee attendance logout saves');
    expect(scalar('SELECT logout_at FROM employee_attendance_sessions WHERE id=?',[$attendanceId])!==null, 'Attendance logout timestamp persists');
    $todayLogin=date('g:i A',strtotime((string)scalar('SELECT login_at FROM employee_attendance_sessions WHERE id=?',[$attendanceId])));
    $attendanceDashboard=$attendanceEmployee->request($dashboards['website'])['body'];
    expect(str_contains($attendanceDashboard,'<h2>Attendance</h2>') && str_contains($attendanceDashboard,$todayLogin), 'Dashboard attendance card shows today login time');
    expect(str_contains($attendanceDashboard,'Logout time'), 'Dashboard attendance card shows today logout time');
    expect(str_contains($attendanceDashboard,'href="employee-attendance.php"'), 'Dashboard attendance card opens attendance page');
    $yesterdayAttendance=date('Y-m-d',strtotime('-1 day'));
    $pdo->prepare('UPDATE employee_profiles SET joining_date=? WHERE user_id=?')->execute([$yesterdayAttendance,$employeeIds['website']]);
    $pdo->prepare('INSERT INTO employee_attendance_sessions (employee_id,login_at) VALUES (?,?)')->execute([$employeeIds['website'],$yesterdayAttendance.' 09:00:00']);
    $attendancePage=$attendanceEmployee->request('employee-attendance.php');
    expect($attendancePage['status']===200 && str_contains($attendancePage['body'],'Attendance by day'), 'Employee attendance page shows day-wise history');
    expect(str_contains($attendancePage['body'],'No complete login/logout recorded'), 'Incomplete past attendance is shown as leave');
    expect(scalar('SELECT status FROM employee_attendance_days WHERE employee_id=? AND attendance_date=?',[$employeeIds['website'],$yesterdayAttendance])==='leave', 'Incomplete past workday leave status is saved');
    $adminAttendanceList=$admin->request('employee-attendance.php');
    expect($adminAttendanceList['status']===200 && str_contains($adminAttendanceList['body'],'Employee website'), 'Admin attendance page lists employees');
    $adminAttendanceDetails=$admin->request('employee-attendance.php?employee='.$employeeIds['website'].'&month='.date('Y-m'));
    expect($adminAttendanceDetails['status']===200 && str_contains($adminAttendanceDetails['body'],'Employee website · Attendance') && str_contains($adminAttendanceDetails['body'],'Attendance by day'), 'Admin opens selected employee attendance history');
    $pdf = tempnam(sys_get_temp_dir(), 'bhavi_payslip_');
    $temporary[] = $pdf;
    $pdfContent = "%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF\n";
    file_put_contents($pdf, $pdfContent);
    $manager->request('payslips.php');
    $payData = ['department_id' => scalar("SELECT id FROM departments WHERE code='website'"), 'employee_id' => $employeeIds['website'], 'pay_month' => date('Y-m'), 'payslip' => new CURLFile($pdf, 'application/pdf', 'salary.pdf')];
    expect($manager->post('payslips.php', array_merge($payData, ['employee_id' => $employeeIds['seo']]))['status'] === 200, 'Payslip department mismatch rejected');
    expect((int)scalar('SELECT COUNT(*) FROM payslips') === 0, 'Invalid payslip not saved');
    expect($manager->post('payslips.php', $payData)['status'] === 303, 'Manager uploads private payslip');
    $payId = (int)scalar('SELECT id FROM payslips LIMIT 1');
    expect($browsers['website']->request('download-payslip.php?id=' . $payId)['body'] === $pdfContent, 'Owner downloads original payslip');
    expect($manager->request('download-payslip.php?id=' . $payId)['body'] === $pdfContent, 'Manager downloads payslip');
    expect($browsers['seo']->request('download-payslip.php?id=' . $payId)['status'] === 404, 'Other employee cannot download payslip by ID');
    expect(!str_contains($browsers['seo']->request('payslips.php')['body'], 'download-payslip.php?id='), 'Other employee cannot list payslip');
    $pdo->prepare('UPDATE employee_profiles SET department_id=? WHERE user_id=?')->execute([$payData['department_id'], $employeeIds['seo']]);
    expect($browsers['seo']->request('download-payslip.php?id=' . $payId)['status'] === 404, 'Same department employee cannot download another payslip');
    expect(!str_contains($browsers['seo']->request('payslips.php')['body'], 'download-payslip.php?id='), 'Same department employee cannot list another payslip');
    $pdo->prepare('UPDATE employee_profiles SET department_id=? WHERE user_id=?')->execute([scalar("SELECT id FROM departments WHERE code='seo'"), $employeeIds['seo']]);
    expect($browsers['website']->post('payslips.php', $payData)['status'] === 403, 'Employee cannot upload payslips');
    expect($guest->request('download-payslip.php?id=' . $payId)['headers']['location'] === 'login.php', 'Anonymous payslip blocked');
    $manager->request('payslips.php');
    expect($manager->post('payslips.php', $payData)['status'] === 200, 'Duplicate employee month rejected');
    expect((int)scalar('SELECT COUNT(*) FROM payslips') === 1, 'Duplicate does not create extra payslip');
    expect($manager->request('payslips.php', ['csrf' => 'invalid'])['status'] === 419, 'Payslip upload requires CSRF');
    file_put_contents($pdf, 'This is not a PDF.');
    $manager->request('payslips.php');
    expect(str_contains($manager->post('payslips.php', array_merge($payData, ['pay_month' => '2025-01']))['body'], 'Only PDF payslips are accepted'), 'Spoofed PDF rejected');
    expect((int)scalar('SELECT COUNT(*) FROM payslips') === 1, 'Invalid PDF not persisted');
    expect(str_contains($manager->request('manager-dashboard.php')['body'], '<strong>5</strong>'), 'Manager total uses database employees');
    expect(str_contains($browsers['website']->request('employee-profile.php')['body'], 'employee-profile-layout'), 'Employee profile uses responsive desktop layout');
    expect($browsers['seo']->request('website-employee-dashboard.php')['headers']['location'] === 'seo-employee-dashboard.php', 'Wrong department route redirects');
    expect(str_contains($browsers['website']->request('admin-employees.php')['body'], 'Employee seo'), 'Employee sees shared employee directory');
    $employeeEdit = ['employee_name' => 'Employee website', 'email' => 'website@example.test', 'username' => 'website.test', 'temporary_password' => '', 'role' => 'admin', 'account_status' => 'active', 'department_id' => scalar("SELECT id FROM departments WHERE code='website'"), 'designation' => 'Senior developer', 'joining_date' => date('Y-m-d'), 'manager_id' => ''];
    $manager->request('admin-add-employee.php?id=' . $employeeIds['website']);
    expect($manager->post('admin-add-employee.php?id=' . $employeeIds['website'], $employeeEdit)['status'] === 303, 'Manager edits employee');
    expect(scalar('SELECT designation FROM employee_profiles WHERE user_id=?', [$employeeIds['website']]) === 'Senior developer', 'Employee edit persists');
    expect(scalar('SELECT role FROM users WHERE id=?', [$employeeIds['website']]) === 'employee', 'Employee form cannot elevate a role');
    expect(password_verify($password, (string)scalar('SELECT password_hash FROM users WHERE id=?', [$employeeIds['website']])), 'Blank edit password keeps existing password');
    $manager->request('admin-add-employee.php?id=' . $employeeIds['website']);
    expect($manager->post('admin-add-employee.php?id=' . $employeeIds['website'], array_merge($employeeEdit, ['account_status' => 'inactive']))['status'] === 303, 'Employee account can be deactivated');
    expect($browsers['website']->request($dashboards['website'])['headers']['location'] === 'login.php', 'Inactive account loses access');
    $manager->request('admin-add-employee.php?id=' . $employeeIds['website']);
    expect($manager->post('admin-add-employee.php?id=' . $employeeIds['website'], $employeeEdit)['status'] === 303, 'Employee account can be reactivated');
    $browsers['website']->login('website.test', $password, $dashboards['website']);
    $admin->request('admin-add-employee.php');
    expect($admin->post('admin-add-employee.php', ['employee_name' => 'Duplicate', 'email' => '', 'username' => 'website.test', 'temporary_password' => $password, 'role' => 'employee', 'account_status' => 'active', 'department_id' => scalar("SELECT id FROM departments WHERE code='website'"), 'designation' => 'Developer', 'joining_date' => date('Y-m-d'), 'manager_id' => ''])['status'] === 200, 'Duplicate username produces form error');
    expect((int)scalar("SELECT COUNT(*) FROM users WHERE role='employee'") === 5, 'Duplicate account transaction rolls back');
    $admin->request('admin-add-client.php');
    expect($admin->post('admin-add-client.php', ['client_name' => 'Unsafe', 'website_url' => 'javascript:alert(1)'])['status'] === 200, 'Unsafe client URL rejected');
    $image = tempnam(sys_get_temp_dir(), 'bhavi_logo_');
    $temporary[] = $image;
    file_put_contents($image, base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='));
    file_put_contents($image, str_repeat("\0", 6 * 1024 * 1024), FILE_APPEND);
    expect($admin->post('admin-add-client.php', ['client_name' => 'Shared Client', 'website_url' => 'https://example.com', 'social_links[0][platform]'=>'Instagram','social_links[0][url]'=>'https://instagram.com/shared','social_links[1][platform]'=>'Pinterest','social_links[1][url]'=>'https://pinterest.com/shared', 'client_logo' => new CURLFile($image, 'image/png', 'logo.png')])['status'] === 303, 'Client and logo upload');
    $clientId = (int)scalar("SELECT id FROM clients WHERE client_name='Shared Client'");
    $uploadedLogo = (string)scalar('SELECT logo_path FROM clients WHERE id=?', [$clientId]);
    if (preg_match('~^uploads/photos/[a-f0-9]{32}\.png$~D', $uploadedLogo)) $temporary[] = dirname(__DIR__) . '/' . $uploadedLogo;
    expect(str_starts_with($uploadedLogo, 'uploads/photos/') && is_file(dirname(__DIR__) . '/' . $uploadedLogo), 'Client logo saved under uploads/photos');
    $logoResponse = $admin->request('client-logo.php?id=' . $clientId);
    expect($logoResponse['status'] === 200 && str_starts_with($logoResponse['headers']['content-type'], 'image/png'), 'Client logo served through protected endpoint');
    expect((int)scalar('SELECT COUNT(*) FROM client_social_links WHERE client_id=?',[$clientId])===2, 'Multiple client social links saved');
    expect(str_contains($admin->request('admin-add-client.php?id='.$clientId)['body'],'Pinterest'), 'Saved social links populate client edit form');
    foreach ([$manager, ...array_values($browsers)] as $browser) expect(str_contains($browser->request('add-client.php')['body'], 'Shared Client'), 'Client visible across roles');
    $admin->request('admin-add-client.php?id=' . $clientId);
    expect($admin->post('admin-add-client.php?id=' . $clientId, ['client_name' => 'Shared Client Updated', 'website_url' => 'https://example.com/new','social_links'=>[['platform'=>'Instagram','url'=>'https://instagram.com/shared'],['platform'=>'Pinterest','url'=>'https://pinterest.com/shared']]])['status'] === 303, 'Client edit');
    expect(scalar('SELECT client_name FROM clients WHERE id=?', [$clientId]) === 'Shared Client Updated', 'Edited client persists');
    $admin->request('admin-holidays.php');
    $holidayDate = date('Y-m-d', strtotime('+20 days'));
    expect($admin->post('admin-holidays.php', ['action' => 'save_holiday', 'holiday_name' => 'Team Holiday <b>', 'holiday_date' => $holidayDate, 'description' => 'Company holiday'])['status'] === 303, 'Holiday creation');
    $holidayId = (int)scalar('SELECT id FROM holidays WHERE holiday_date=?', [$holidayDate]);
    foreach ([$manager, ...array_values($browsers)] as $browser) {
        $body = $browser->request('admin-holidays.php')['body'];
        expect(str_contains($body, 'Team Holiday &lt;b&gt;') && !str_contains($body, 'Team Holiday <b>'), 'Shared holiday and output escaping');
        expect(str_contains($body, 'Company holiday'), 'Holiday description visible to every role');
    }
    $manager->request('admin-holidays.php?edit=' . $holidayId);
    expect($manager->post('admin-holidays.php?edit=' . $holidayId, ['action' => 'save_holiday', 'holiday_name' => 'Updated Holiday', 'holiday_date' => $holidayDate, 'description' => 'Edited by manager'])['status'] === 303, 'Manager holiday editing');
    $manager->request('manager-assign-work.php');
    $websiteDepartment = (int)scalar("SELECT id FROM departments WHERE code='website'");
    $assignmentDate = date('Y-m-d', strtotime('+1 day'));
    $assignmentData = ['department_id' => $websiteDepartment, 'employee_id' => $employeeIds['website'], 'client_id' => $clientId, 'work_date' => $assignmentDate, 'tasks' => [['title'=>'Build home page','description'=>'Responsive page with contact form'],['title'=>'Add contact form','description'=>'Validate and style the form']]];
    expect(str_contains($manager->request('manager-assign-work.php')['body'],'assets/js/records.js') && str_contains($admin->request('manager-assign-work.php')['body'],'data-add-assignment-task'),'Assignment page loads the Add task handler for both staff roles');
    expect($manager->post('manager-assign-work.php', array_merge($assignmentData, ['employee_id' => $employeeIds['seo']]))['status'] === 200, 'Employee department mismatch rejected');
    expect((int)scalar('SELECT COUNT(*) FROM work_assignments') === 0, 'Invalid assignment never saved');
    expect($manager->post('manager-assign-work.php', $assignmentData)['status'] === 303, 'Manager assigns work');
    expect((int)scalar('SELECT COUNT(*) FROM work_assignments')===2,'Multiple task briefs are saved as individual assignments');
    $assignmentId = (int)scalar('SELECT id FROM work_assignments ORDER BY id LIMIT 1');
    expect(str_contains($browsers['website']->request('employee-assigned-work.php')['body'], 'Build home page'), 'Assignment visible to its employee');
    expect(str_contains($browsers['website']->request($dashboards['website'])['body'],'href="employee-assigned-work.php"><h2>Today\'s work</h2><strong>2</strong>'),'Upcoming tasks are included in employee assigned-work dashboard count');
    expect(str_contains($browsers['website']->request('employee-assigned-work.php')['body'], 'assignment_date=' . $assignmentDate), 'Future assignment appears in the date list');
    expect(str_contains($browsers['website']->request('employee-assigned-work.php?assignment_date=' . $assignmentDate)['body'], 'Responsive page with contact form'), 'Selecting an assignment date shows its full work brief');
    expect(str_contains($browsers['website']->request('employee-assigned-work.php?assignment_date=' . $assignmentDate)['body'], 'Task 2 · Add contact form'), 'Employee sees each assigned task numbered separately');
    expect(!str_contains($browsers['seo']->request('employee-assigned-work.php')['body'], 'Build home page'), 'Assignment hidden from another employee');
    expect($browsers['seo']->post($dashboards['seo'], ['action' => 'update_assignment', 'assignment_id' => $assignmentId, 'task_status' => 'completed', 'remark' => 'Attack'])['status'] === 403, 'Assignment ownership enforced');
    $website = $browsers['website'];
    $website->request('employee-assigned-work.php?assignment_date=' . $assignmentDate);
    $update = ['action' => 'update_assignment', 'assignment_id' => $assignmentId, 'task_status' => 'completed', 'time_spent_hours'=>'1 hour 30 min', 'remark' => '=SUM(1,2)', 'website_new_count' => '2', 'website_changes_count' => '1'];
    expect($website->post('employee-assigned-work.php?assignment_date=' . $assignmentDate, $update)['status'] === 303, 'Employee updates future assignment in today report');
    $website->request('employee-assigned-work.php?assignment_date=' . $assignmentDate);
    expect($website->post('employee-assigned-work.php?assignment_date=' . $assignmentDate, $update)['status'] === 303, 'Repeated update');
    expect((int)scalar('SELECT COUNT(*) FROM daily_work_entries WHERE assignment_id=?', [$assignmentId]) === 1, 'Repeated task update does not duplicate report rows');
    expect(scalar('SELECT work_date FROM daily_work_submissions WHERE id=(SELECT submission_id FROM daily_work_entries WHERE assignment_id=? LIMIT 1)', [$assignmentId]) === date('Y-m-d'), 'Future assignment completion saves under today date');
    expect(scalar('SELECT status FROM work_assignments WHERE id=?', [$assignmentId]) === 'completed', 'Task status persists');
    expect((int)scalar('SELECT time_spent_minutes FROM work_assignments WHERE id=?',[$assignmentId])===90 && (int)scalar('SELECT time_spent_minutes FROM daily_work_entries WHERE assignment_id=?',[$assignmentId])===90,'Employee time spent is saved as minutes on assignment and work history');
    expect(str_contains($admin->request('manager-assigned-status.php?employee='.$employeeIds['website'])['body'],'=SUM(1,2)') && str_contains($admin->request('manager-assigned-status.php?employee='.$employeeIds['website'])['body'],'1 hour 30 min'),'Admin sees readable duration and employee remark');
    expect((int)scalar("SELECT COUNT(*) FROM notifications WHERE recipient_id=(SELECT id FROM users WHERE username='admin.test') AND title LIKE '%assigned task update%' AND message LIKE '%1 hour 30 min%' AND message LIKE '%=SUM(1,2)%'")>0,'Admin receives submitted task status, readable time, and employee remark');
    expect(str_contains($website->request('employee-assigned-work.php?assignment_date='.$assignmentDate)['body'],'assets/js/assignment-duration.js'),'Employee assigned work loads the readable duration input');
    foreach ($dashboards as $code => $dashboard) {
        $browser = $browsers[$code];
        $browser->request($dashboard);
        $metrics = match ($code) {
            'website' => ['website_new_count' => '1', 'website_changes_count' => '0'],
            'seo' => ['seo_quantity' => '3.50', 'seo_quantity_unit' => 'pages'],
            'design_video' => ['video_count' => '1', 'poster_count' => '2', 'carousel_count' => '1', 'design_changes_count' => '0'],
            'telecaller' => ['calls_count' => '10', 'connected_count' => '5', 'followups_count' => '3', 'leads_count' => '2'],
            'social_media' => ['social_platform' => 'Instagram', 'posts_count' => '2', 'reels_count' => '1', 'replies_count' => '6']
        };
        $work = array_merge(['action' => 'save_entry', 'client_id' => $clientId, 'task_title' => $code . ' daily task', 'task_status' => 'completed', 'remark' => 'Daily ' . $code, 'submit_mode' => 'submitted'], $metrics);
        expect($browser->post($dashboard, $work)['status'] === 303, 'Department work submission ' . $code);
    }
    $tele = $browsers['telecaller'];
    $tele->request($dashboards['telecaller']);
    expect($tele->post($dashboards['telecaller'], ['action' => 'save_entry', 'client_id' => $clientId, 'task_title' => 'Bad counts', 'task_status' => 'pending', 'remark' => '', 'calls_count' => '1', 'connected_count' => '2', 'followups_count' => '0', 'leads_count' => '0'])['status'] === 200, 'Invalid telecaller quantities rejected');
    $yesterday = date('Y-m-d', strtotime('-1 day'));
    $website->request($dashboards['website'] . '?date=' . $yesterday);
    expect($website->post($dashboards['website'] . '?date=' . $yesterday, ['action' => 'save_entry', 'client_id' => $clientId, 'task_title' => 'Yesterday page', 'task_status' => 'pending', 'remark' => 'Historic work', 'website_new_count' => '1', 'website_changes_count' => '0', 'submit_mode' => 'draft'])['status'] === 303, 'Draft save');
    expect(scalar('SELECT submission_status FROM daily_work_submissions WHERE employee_id=? AND work_date=?', [$employeeIds['website'], $yesterday]) === 'draft', 'Draft status persists');
    $website->request($dashboards['website'] . '?date=' . $yesterday);
    expect($website->post($dashboards['website'] . '?date=' . $yesterday, ['action' => 'submit_day'])['status'] === 303, 'Submit entire day');
    $manager->request('manager-dailywork.php');
    $all = $manager->request('manager-dailywork.php')['body'];
    expect(str_contains($all, 'website daily task') && str_contains($all, 'seo daily task'), 'All submitted departments appear in report details');
    $filtered = $manager->request('manager-dailywork.php?department=' . $websiteDepartment)['body'];
    expect(str_contains($filtered, 'website daily task') && !str_contains($filtered, 'seo daily task'), 'Department report filtering');
    expect(!str_contains($filtered, '>Employee seo</option>'), 'Category dropdown lists matching employees');
    expect($manager->request('manager-dailywork.php?from_date=invalid')['status'] === 422, 'Invalid report date rejected');
    $excel = $manager->request('download-work.php?from_date=' . $yesterday . '&to_date=' . date('Y-m-d') . '&department=' . $websiteDepartment);
    expect(str_contains($excel['headers']['content-type'], 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet') && str_contains($excel['headers']['content-disposition'], '.xlsx'), 'Excel download headers');
    expect(str_starts_with($excel['body'], 'PK'), 'Excel download is a ZIP workbook');
    $excelPath = tempnam(sys_get_temp_dir(), 'bhavi_report_');
    $temporary[] = $excelPath;
    file_put_contents($excelPath, $excel['body']);
    $workbook = new ZipArchive();
    expect($workbook->open($excelPath) === true, 'Excel workbook opens');
    $sheet = $workbook->getFromName('xl/worksheets/sheet1.xml');
    $workbook->close();
    expect(str_contains($sheet, 'Yesterday page') && str_contains($sheet, 'website daily task') && !str_contains($sheet, 'seo daily task'), 'Excel range and department filtering');
    expect(str_contains($sheet, '=SUM(1,2)') && str_contains($sheet, 'inlineStr'), 'Excel formula-looking text stays a literal string');
    $allDatesPage=$manager->request('manager-dailywork.php?all_dates=1&employee='.$employeeIds['website']);
    expect(str_contains($allDatesPage['body'],'name="all_dates" value="1"') && str_contains($allDatesPage['body'],'All dates'),'All-dates report filter is available for an employee');
    $allDatesExcel=$manager->request('download-work.php?all_dates=1&employee='.$employeeIds['website']);
    $allDatesPath=tempnam(sys_get_temp_dir(),'bhavi_all_dates_');
    $temporary[]=$allDatesPath;
    file_put_contents($allDatesPath,$allDatesExcel['body']);
    $allDatesWorkbook=new ZipArchive();
    expect($allDatesWorkbook->open($allDatesPath)===true,'Employee all-dates Excel workbook opens');
    $allDatesSheet=$allDatesWorkbook->getFromName('xl/worksheets/sheet1.xml');
    $allDatesWorkbook->close();
    expect(str_contains($allDatesSheet,'Yesterday page') && str_contains($allDatesSheet,'website daily task') && str_contains($allDatesSheet,'1 hour 30 min') && !str_contains($allDatesSheet,'seo daily task'),'All-dates Excel includes selected employee history and time without other employees');
    $employeeExcel = $manager->request('download-work.php?employee=' . $employeeIds['seo']);
    $employeePath = tempnam(sys_get_temp_dir(), 'bhavi_report_');
    $temporary[] = $employeePath;
    file_put_contents($employeePath, $employeeExcel['body']);
    $employeeWorkbook = new ZipArchive();
    expect($employeeWorkbook->open($employeePath) === true, 'Employee Excel workbook opens');
    $employeeSheet = $employeeWorkbook->getFromName('xl/worksheets/sheet1.xml');
    $employeeWorkbook->close();
    expect(str_contains($employeeSheet, 'seo daily task') && !str_contains($employeeSheet, 'website daily task'), 'Employee Excel filter');
    ob_start();
    download_csv(['Task','Remark'],[['Page update','=SUM(1,2)'],['Follow-up','Issue, needs review']],'bhavi-fallback-test');
    $csvFallback=ob_get_clean();
    expect(str_starts_with($csvFallback,"\xEF\xBB\xBFTask,Remark") && str_contains($csvFallback,"'=SUM(1,2)") && str_contains($csvFallback,'"Issue, needs review"'),'CSV fallback is Excel-readable, preserves comma fields, and neutralizes formula input');
    $sheetId = (int)scalar('SELECT id FROM daily_work_submissions WHERE employee_id=? AND work_date=?', [$employeeIds['website'], date('Y-m-d')]);
    $manager->request('manager-review-work.php?id=' . $sheetId);
    expect($manager->post('manager-review-work.php?id=' . $sheetId, ['action' => 'review_sheet', 'review_status' => 'changes_requested', 'manager_remark' => 'Please update the mobile header'])['status'] === 303, 'Manager reviews work');
    expect(str_contains($website->request('employee-work-history.php')['body'], 'Please update the mobile header'), 'Employee sees manager feedback');
    $entryId = (int)scalar('SELECT id FROM daily_work_entries WHERE assignment_id=?', [$assignmentId]);
    $manager->request('manager-review-work.php?id=' . $sheetId);
    expect($manager->post('manager-review-work.php?id=' . $sheetId, ['action' => 'edit_entry', 'entry_id' => $entryId, 'task_title' => 'Reviewed home page', 'task_status' => 'pending', 'remark' => 'Needs revision', 'website_new_count' => '1', 'website_changes_count' => '2'])['status'] === 303, 'Manager edits submitted work');
    expect(scalar('SELECT status FROM work_assignments WHERE id=?', [$assignmentId]) === 'pending', 'Manager work edit synchronizes assignment');
    $leaveDate = (new DateTimeImmutable('next tuesday'))->format('Y-m-d');
    $website->request('apply-leaves.php');
    $leaveData = ['leave_type_id' => '1', 'from_date' => $leaveDate, 'to_date' => $leaveDate, 'reason' => 'Family appointment'];
    expect($website->post('apply-leaves.php', $leaveData)['status'] === 303, 'Employee applies leave');
    $leaveId = (int)scalar('SELECT id FROM leave_requests WHERE employee_id=? ORDER BY id DESC LIMIT 1', [$employeeIds['website']]);
    expect((int)scalar("SELECT COUNT(*) FROM notifications WHERE leave_request_id=? AND notification_type='leave_applied' AND recipient_id IN (SELECT id FROM users WHERE role IN ('admin','manager'))",[$leaveId])===2,'Admins and managers receive employee leave notifications');
    $website->request('apply-leaves.php');
    expect($website->post('apply-leaves.php', $leaveData)['status'] === 200, 'Overlapping leave rejected');
    expect(str_contains($manager->request('manager-leave-requist.php')['body'], 'Family appointment'), 'Manager sees leave request');
    expect($manager->post('manager-leave-requist.php', ['id' => $leaveId, 'decision' => 'approved', 'decision_note' => 'Approved by manager'])['status'] === 303, 'Manager approves leave');
    expect(scalar('SELECT status FROM leave_requests WHERE id=?', [$leaveId]) === 'approved', 'Approval persists');
    expect(str_contains($website->request('my-leave-requests.php')['body'], 'Approved by manager'), 'Employee sees leave decision');
    expect(str_contains($website->request('check-leave.php?month=' . substr($leaveDate, 0, 7))['body'], 'Personal · approved'), 'Leave calendar uses stored approval');
    $attendanceLeavePage=$website->request('employee-attendance.php?month='.substr($leaveDate,0,7));
    expect(str_contains($attendanceLeavePage['body'],'Personal ·') && str_contains($attendanceLeavePage['body'],'approved'), 'Attendance page includes approved leave dates');
    $manager->request('manager-leave-requist.php');
    expect($manager->post('manager-leave-requist.php', ['id' => $leaveId, 'decision' => 'rejected', 'decision_note' => 'Second decision'])['status'] === 200, 'Repeat leave decision rejected');
    expect(scalar('SELECT status FROM leave_requests WHERE id=?', [$leaveId]) === 'approved', 'Original decision preserved');
    $seo = $browsers['seo'];
    $seo->request('apply-leaves.php');
    expect($seo->post('apply-leaves.php', array_merge($leaveData, ['reason' => 'SEO leave']))['status'] === 303, 'Second employee leave');
    $seoLeave = (int)scalar('SELECT id FROM leave_requests WHERE employee_id=? ORDER BY id DESC LIMIT 1', [$employeeIds['seo']]);
    $manager->request('manager-leave-requist.php');
    expect($manager->post('manager-leave-requist.php', ['id' => $seoLeave, 'decision' => 'rejected', 'decision_note' => 'Discuss new dates'])['status'] === 303, 'Manager rejects leave');
    expect(str_contains($seo->request('my-leave-requests.php')['body'], 'Discuss new dates'), 'Rejected decision visible');
    expect(!str_contains($seo->request('my-leave-requests.php')['body'], 'Family appointment'), 'Leave history is private');
    $seo->request('apply-leaves.php');
    expect($seo->post('apply-leaves.php', array_merge($leaveData, ['reason' => 'Request to cancel']))['status'] === 303, 'Leave can be reapplied after rejection');
    $cancelId = (int)scalar('SELECT id FROM leave_requests WHERE employee_id=? ORDER BY id DESC LIMIT 1', [$employeeIds['seo']]);
    $website->request('apply-leaves.php');
    expect($website->post('apply-leaves.php', ['action' => 'cancel_leave', 'id' => $cancelId])['status'] === 200, 'Employee cannot cancel another employee leave');
    $seo->request('apply-leaves.php');
    expect($seo->post('apply-leaves.php', ['action' => 'cancel_leave', 'id' => $cancelId])['status'] === 303, 'Employee can cancel own pending request');
    expect(scalar('SELECT status FROM leave_requests WHERE id=?', [$cancelId]) === 'cancelled', 'Cancelled leave persists');
    expect(!str_contains($manager->request('manager-leave-requist.php')['body'], 'Request to cancel'), 'Cancelled employee leave is hidden from manager');
    $website->request('employee-brands-assets.php');
    expect(str_contains($website->request('client-reuirement.php')['body'], 'Responsive page with contact form'), 'Client requirements show assigned brief');
    expect(str_contains($admin->request('manager-leave-requist.php')['body'],'Family appointment'), 'Admin can view employee leave requests');
    $adminLeaveDate=(new DateTimeImmutable('next wednesday'))->format('Y-m-d');
    $website->request('apply-leaves.php');
    expect($website->post('apply-leaves.php',array_merge($leaveData,['from_date'=>$adminLeaveDate,'to_date'=>$adminLeaveDate,'reason'=>'Admin approval test']))['status']===303,'Employee submits leave for admin review');
    $adminLeaveId=(int)scalar('SELECT id FROM leave_requests WHERE employee_id=? AND reason=? ORDER BY id DESC LIMIT 1',[$employeeIds['website'],'Admin approval test']);
    expect(str_contains($admin->request('manager-leave-requist.php?status=pending')['body'],'Admin approval test'),'Admin sees pending employee leave');
    expect($admin->post('manager-leave-requist.php',['id'=>$adminLeaveId,'decision'=>'approved','decision_note'=>'Approved by admin'])['status']===303,'Admin can approve employee leave');
    expect(scalar('SELECT status FROM leave_requests WHERE id=?',[$adminLeaveId])==='approved' && (int)scalar('SELECT decided_by FROM leave_requests WHERE id=?',[$adminLeaveId])===(int)scalar("SELECT id FROM users WHERE username='admin.test'"),'Admin leave approval is saved with approver');
    expect(str_contains($website->request('my-leave-requests.php')['body'],'Approved by admin'),'Employee sees admin leave decision');
    expect($admin->post('manager-leave-requist.php',['action'=>'delete_leave','id'=>$adminLeaveId])['status']===403,'Admin cannot delete employee leave requests');
    expect(!str_contains($manager->request('manager-dashboard.php')['body'], 'Upcoming holidays'), 'Manager dashboard omits holiday card');
    $admin->request('departments.php');
    expect($admin->post('departments.php', ['name' => 'Quality Assurance'])['status'] === 303, 'Admin adds department');
    $newDepartment = (int)scalar("SELECT id FROM departments WHERE name='Quality Assurance'");
    expect(str_contains($admin->request('admin-add-employee.php')['body'], 'Quality Assurance'), 'New department appears in employee form');
    $admin->request('departments.php?edit=' . $newDepartment);
    expect($admin->post('departments.php?edit=' . $newDepartment, ['name' => 'Quality Engineering'])['status'] === 303, 'Admin edits department');
    expect(str_contains($admin->request('admin-add-employee.php')['body'], 'Quality Engineering'), 'Renamed department appears in employee form');
    expect($manager->request('departments.php')['status'] === 403, 'Department management is admin only');
    $admin->request('departments.php');
    expect(str_contains($admin->post('departments.php', ['action' => 'delete_department', 'id' => $websiteDepartment])['body'], 'Move the employees'), 'Populated department deletion prevented');
    expect($admin->post('departments.php', ['action' => 'delete_department', 'id' => $newDepartment])['status'] === 303, 'Unused department deleted');
    expect((int)scalar('SELECT is_active FROM departments WHERE id=?', [$newDepartment]) === 0, 'Department deletion persists');
    expect(!str_contains($admin->request('admin-add-employee.php')['body'], 'Quality Engineering'), 'Deleted department removed from employee choices');
    $manager->request('manager-leave-requist.php');
    expect($manager->post('manager-leave-requist.php', ['action' => 'save_note', 'id' => $leaveId, 'decision_note' => 'Please complete the handover <today>'])['status'] === 303, 'Manager sends a follow-up leave note');
    expect(scalar('SELECT status FROM leave_requests WHERE id=?', [$leaveId]) === 'approved', 'Follow-up note preserves decision');
    expect(str_contains($website->request('my-leave-requests.php')['body'], 'Please complete the handover &lt;today&gt;'), 'Employee sees escaped manager message in request history');
    expect(str_contains($website->request('manager-notification.php')['body'], 'Please complete the handover &lt;today&gt;'), 'Employee receives leave note notification');
    expect(!str_contains($seo->request('manager-notification.php')['body'], 'Please complete the handover'), 'Leave message private to recipient');
    expect($website->post('manager-leave-requist.php', ['action' => 'delete_leave', 'id' => $seoLeave])['status'] === 403, 'Employee cannot delete leave requests');
    expect($manager->request('manager-leave-requist.php', ['csrf' => 'invalid', 'action' => 'delete_leave', 'id' => $seoLeave])['status'] === 419, 'Leave deletion requires CSRF');
    $manager->request('manager-leave-requist.php');
    expect($manager->post('manager-leave-requist.php', ['action' => 'delete_leave', 'id' => $seoLeave])['status'] === 303, 'Manager deletes decided leave request');
    expect((int)scalar('SELECT COUNT(*) FROM leave_requests WHERE id=?', [$seoLeave]) === 0, 'Deleted leave removed from database');
    expect((int)scalar('SELECT COUNT(*) FROM notifications WHERE leave_request_id=?', [$seoLeave]) === 0, 'Leave notification links detached on deletion');
    $manager->request('manager-notification.php');
    expect($manager->post('manager-notification.php', ['action' => 'send_notification', 'department_id' => $websiteDepartment, 'employee_id' => $employeeIds['website'], 'title' => 'Project update', 'message' => 'Please review the brief'])['status'] === 303, 'Manager sends employee notification');
    $notificationPage = $website->request('manager-notification.php')['body'];
    expect(str_contains($notificationPage, 'Please review the brief') && !str_contains($notificationPage, 'notification-link'), 'Notification messages remain present inside date groups');
    expect(str_contains($notificationPage, '<details class="panel notification-day">') && str_contains($notificationPage, 'notifications</span></summary>'), 'Notification dates have expandable counts');
    $pdo->prepare("INSERT INTO notifications (recipient_id,notification_type,title,message,created_at) VALUES (?,'general','Yesterday test','Older daily notification',DATE_SUB(NOW(),INTERVAL 1 DAY))")->execute([$employeeIds['website']]);
    $dailyPage = $website->request('manager-notification.php')['body'];
    expect(str_contains($dailyPage, date('l, d M Y', strtotime('-1 day'))) && str_contains($dailyPage, 'Older daily notification'), 'Previous day appears as its own notification group');
    expect(!str_contains($manager->request('manager-notification.php')['body'], 'Older daily notification'), 'Daily notifications remain private to recipient');
    expect(str_contains($notificationPage, 'href="manager-notification.php"'), 'Notifications menu opens the notification page');
    $website->request('employee-daily-work.php');
    expect($website->post('employee-daily-work.php', ['action' => 'save_entry', 'client_id' => '', 'task_title' => 'Internal planning without client', 'task_status' => 'completed', 'remark' => 'Team planning', 'website_new_count' => '', 'website_changes_count' => '', 'submit_mode' => 'submitted'])['status'] === 303, 'Daily work saves with blank optional client and metrics');
    expect(str_contains($website->request('employee-work-history.php')['body'], 'Internal planning without client'), 'Employee sees submitted internal work');
    expect(str_contains($manager->request('manager-dailywork.php')['body'], 'Internal planning without client'), 'Manager sees internal work without client');
    expect(str_contains($admin->request('manager-dailywork.php')['body'], 'Internal planning without client'), 'Admin sees same internal work report');
    expect(!str_contains($website->request('employee-daily-work.php')['body'], 'id="assigned-work"'), 'Daily work screen excludes assignments');
    expect(!str_contains($website->request('employee-assigned-work.php')['body'], 'name="website_new_count"'), 'Assignment form only requests status and remark');
    expect(str_contains($manager->request('manager-assigned-status.php')['body'], 'Employees completed all work'), 'Assignment progress summary available');
    $largePdf = tempnam(sys_get_temp_dir(), 'bhavi_document_');
    $temporary[] = $largePdf;
    $admin->request('admin-add-employee.php?id=' . $employeeIds['website']);
    $missingDepartment = $admin->post('admin-add-employee.php?id=' . $employeeIds['website'], array_merge($employeeEdit, ['department_id' => '', 'documents[0]' => new CURLFile($image, 'image/png', 'photo.png')]));
    expect(str_contains($missingDepartment['body'], 'Please select a department for this employee.'), 'Image upload with missing department shows the specific field error');
    expect(!str_contains($missingDepartment['body'], 'Please select a valid record.'), 'Employee form avoids generic record error');
    expect(str_contains($missingDepartment['body'], 'Please select your documents again'), 'Validation failure explains file reselection');
    expect((int)scalar('SELECT COUNT(*) FROM employee_documents WHERE employee_id=?', [$employeeIds['website']]) === 0, 'Invalid form does not save partial documents');
    file_put_contents($largePdf, "%PDF-1.4\n" . str_repeat(' ', 3 * 1024 * 1024) . "\n%%EOF");
    $admin->request('admin-add-employee.php?id=' . $employeeIds['website']);
    $docResponse = $admin->post('admin-add-employee.php?id=' . $employeeIds['website'], array_merge($employeeEdit, ['role_title' => 'Web developer', 'employee_photo' => new CURLFile($image, 'image/png', 'avatar.png'), 'documents[0]' => new CURLFile($largePdf, 'application/pdf', 'employment.pdf'), 'documents[1]' => new CURLFile($image, 'image/png', 'employee-photo.png')]));
    $documentId = (int)scalar("SELECT id FROM employee_documents WHERE employee_id=? AND original_name='employment.pdf'", [$employeeIds['website']]);
    $documentPaths = $pdo->prepare('SELECT file_path FROM employee_documents WHERE employee_id=?');
    $documentPaths->execute([$employeeIds['website']]);
    foreach ($documentPaths->fetchAll(PDO::FETCH_COLUMN) as $documentPath) $temporary[] = dirname(__DIR__) . '/' . $documentPath;
    $avatar = (string)scalar('SELECT avatar_path FROM users WHERE id=?', [$employeeIds['website']]);
    if ($avatar) $temporary[] = dirname(__DIR__) . '/' . $avatar;
    expect(str_starts_with($avatar, 'uploads/photos/') && is_file(dirname(__DIR__) . '/' . $avatar), 'Employee avatar path and file saved');
    expect($manager->request('employee-photo.php?id=' . $employeeIds['website'])['body'] === file_get_contents($image), 'Manager can view employee photo');
    expect(str_contains($manager->request('admin-employees.php')['body'], 'employee-photo.php?id=' . $employeeIds['website']), 'Manager directory shows employee photo');
    expect($website->request('employee-photo.php?id=' . $employeeIds['website'])['status'] === 200, 'Employee can view own photo');
    expect($browsers['seo']->request('employee-photo.php?id=' . $employeeIds['website'])['status'] === 200, 'Employees can view shared directory photos');
    expect(str_starts_with((string)scalar('SELECT file_path FROM employee_documents WHERE id=?', [$documentId]), 'uploads/pdf/'), 'PDF path saved under uploads/pdf');
    expect($docResponse['status'] === 303 && $documentId > 0, 'Employee PDF larger than old 2 MB limit uploads');
    expect(scalar('SELECT role_title FROM employee_profiles WHERE user_id=?', [$employeeIds['website']]) === 'Web developer', 'Custom job title saved');
    expect($manager->request('download-employee-document.php?id=' . $documentId)['body'] === file_get_contents($largePdf), 'Manager downloads original private document');
    expect($website->request('download-employee-document.php?id=' . $documentId)['status'] === 403, 'Employees cannot download HR documents');
    expect(str_contains($admin->request('admin-add-employee.php?id=' . $employeeIds['website'])['body'], 'employment.pdf'), 'Uploaded document remains visible on employee edit');
    expect((int)scalar('SELECT COUNT(*) FROM employee_documents WHERE employee_id=?', [$employeeIds['website']]) === 2, 'Multiple PDF and image documents uploaded together');
    expect(str_contains($docResponse['headers']['location'], '#saved-documents'), 'Successful upload opens the saved documents list');
    if (!getenv('BHAVI_SKIP_LARGE_UPLOAD_TEST')) {
        echo "Checking 100 MB document upload...\n";
    $handle = fopen($largePdf, 'wb');
    fwrite($handle, "%PDF-1.4\n");
    $block=str_repeat(' ',1024*1024);
        for ($chunk=0;$chunk<99;$chunk++) fwrite($handle,$block);
        fwrite($handle,substr($block,9));
    fclose($handle);
    expect($admin->post('admin-add-employee.php?id=' . $employeeIds['website'], array_merge($employeeEdit, ['documents[0]' => new CURLFile($largePdf, 'application/pdf', 'exact-limit.pdf')]))['status'] === 303, 'Exactly 100 MB PDF accepted');
        echo "100 MB accepted; checking over-limit rejection...\n";
    $limitPath = (string)scalar("SELECT file_path FROM employee_documents WHERE original_name='exact-limit.pdf'");
    $temporary[] = dirname(__DIR__) . '/' . $limitPath;
    expect(filesize(dirname(__DIR__) . '/' . $limitPath) === 100 * 1024 * 1024, '100 MB document persisted intact');
    $handle = fopen($largePdf, 'ab');
    fwrite($handle, 'x');
    fclose($handle);
    expect(str_contains($admin->post('admin-add-employee.php?id=' . $employeeIds['website'], array_merge($employeeEdit, ['documents[0]' => new CURLFile($largePdf, 'application/pdf', 'too-large.pdf')]))['body'], '100 MB'), 'Document above 100 MB rejected clearly');
    expect((int)scalar('SELECT COUNT(*) FROM employee_documents WHERE employee_id=?', [$employeeIds['website']]) === 3, 'Rejected upload does not create document row');
        echo "Upload size boundaries passed.\n";
    }
    $admin->request('admin-add-employee.php?id=' . $employeeIds['website']);
    expect($admin->post('admin-add-employee.php?id=' . $employeeIds['website'], $employeeEdit)['status'] === 303, 'Employee edit without photo succeeds');
    expect(scalar('SELECT avatar_path FROM users WHERE id=?', [$employeeIds['website']]) === $avatar, 'Blank photo preserves existing avatar');
    $gif = tempnam(sys_get_temp_dir(), 'bhavi_gif_');
    $temporary[] = $gif;
    file_put_contents($gif, base64_decode('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'));
    $svg = tempnam(sys_get_temp_dir(), 'bhavi_svg_');
    $temporary[] = $svg;
    file_put_contents($svg, '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10" fill="blue"/></svg>');
    $admin->request('admin-add-employee.php');
    $newEmployee = $admin->post('admin-add-employee.php', array_merge($employeeEdit, ['employee_name' => 'Upload Test', 'username' => 'upload.test', 'email' => 'upload@example.test', 'temporary_password' => $password, 'documents[0]' => new CURLFile($gif, 'image/gif', 'photo.gif'), 'documents[1]' => new CURLFile($svg, 'image/svg+xml', 'photo.svg')]));
    $uploadEmployee = (int)scalar("SELECT id FROM users WHERE username='upload.test'");
    $uploadedDocuments = $pdo->prepare('SELECT id,file_path,mime_type FROM employee_documents WHERE employee_id=?');
    $uploadedDocuments->execute([$uploadEmployee]);
    $uploadedDocuments = $uploadedDocuments->fetchAll();
    foreach ($uploadedDocuments as $document) $temporary[] = dirname(__DIR__) . '/' . $document['file_path'];
    foreach ($uploadedDocuments as $document) expect(str_starts_with($document['file_path'], 'uploads/photos/') && is_file(dirname(__DIR__) . '/' . $document['file_path']), 'Image database record points to a saved uploads/photos file');
    expect($newEmployee['status'] === 303 && count($uploadedDocuments) === 2, 'New employee creation uploads GIF and SVG images');
    foreach ($uploadedDocuments as $document) {
        $download = $admin->request('download-employee-document.php?id=' . $document['id']);
        expect($download['body'] === file_get_contents($document['mime_type'] === 'image/svg+xml' ? $svg : $gif), 'Image document download preserves original bytes');
        if ($document['mime_type'] === 'image/svg+xml') expect(str_contains($download['headers']['content-disposition'], 'attachment') && $download['headers']['content-type'] === 'application/octet-stream', 'SVG downloaded as a private attachment');
    }
    $admin->request('admin-employees.php');
    expect($admin->post('admin-employees.php', ['action' => 'delete_employee', 'id' => $uploadEmployee])['status'] === 303, 'Upload test employee removed from active directory');
    // Employee salary history, exact deductions, ownership and client payment persistence.
    $admin->request('admin-add-employee.php?id=' . $employeeIds['website']);
    $salaryData = array_merge($employeeEdit, ['employee_code' => 'BH-001', 'phone' => '9000011111', 'guardian_phone' => '9000022222', 'benefit_pf' => '1', 'benefit_esi' => '1', 'benefit_other' => '1', 'other_benefits' => 'Travel allowance', 'salary' => [['amount' => '14000', 'from' => date('Y-m-d'), 'to' => ''], ['amount' => '16000', 'from' => date('Y-m-d', strtotime('+1 month')), 'to' => '']]]);
    expect($admin->post('admin-add-employee.php?id=' . $employeeIds['website'], $salaryData)['status'] === 303, 'Employee fields and multiple salary periods saved');
    $salaryId = (int)scalar('SELECT id FROM employee_salary_history WHERE employee_id=? ORDER BY effective_from LIMIT 1', [$employeeIds['website']]);
    expect(scalar('SELECT employee_code FROM employee_profiles WHERE user_id=?', [$employeeIds['website']]) === 'BH-001', 'Employee ID saved');
    expect(scalar('SELECT guardian_phone FROM employee_profiles WHERE user_id=?', [$employeeIds['website']]) === '9000022222', 'Guardian phone saved');
    foreach (['pf_base' => '7000.00', 'esi_base' => '7000.00', 'employee_pf' => '840.00', 'company_pf' => '840.00', 'employee_esi' => '52.50', 'company_esi' => '227.50', 'net_salary' => '13107.50'] as $column => $expected) expect(scalar('SELECT ' . $column . ' FROM employee_salary_history WHERE id=?', [$salaryId]) === $expected, 'Salary calculation ' . $column);
    expect(scalar('SELECT effective_to FROM employee_salary_history WHERE id=?', [$salaryId]) === date('Y-m-d', strtotime(date('Y-m-d', strtotime('+1 month')) . ' -1 day')), 'Increment closes preceding salary period');
    expect(str_contains($website->request('employee-profile.php')['body'], '13,107.50'), 'Employee sees own take-home salary');
    expect(str_contains($admin->request('employee-profile.php?id=' . $employeeIds['website'])['body'], '227.50'), 'Admin sees company ESI');
    expect($browsers['seo']->request('employee-profile.php?id=' . $employeeIds['website'])['status'] === 403, 'Other employee salary URL forbidden');
    expect(!str_contains($browsers['seo']->request('employee-profile.php')['body'], '13,107.50'), 'Other profile does not leak salary');
    expect(!str_contains($website->request('admin-employees.php')['body'], '9000022222'), 'Guardian details excluded from shared directory');
    $adminEmployeeDirectory=$admin->request('admin-employees.php')['body'];
    $staffVisibleFields=['BH-001','9000011111','PF, ESI, Other','employee-photo.php?id='.$employeeIds['website']];
    foreach ($staffVisibleFields as $field) expect(str_contains($website->request('admin-employees.php')['body'],$field), 'Employee directory shows staff field '.$field);
    expect(str_contains($adminEmployeeDirectory,'admin-add-employee.php?id='.$employeeIds['website']) && !str_contains($website->request('admin-employees.php')['body'],'admin-add-employee.php?id='.$employeeIds['website']), 'Only management sees employee edit controls');
    expect(!str_contains($website->request('admin-employees.php')['body'],'name="action" value="delete_employee"'), 'Employee directory hides delete controls');
    expect($website->post('admin-add-employee.php?id=' . $employeeIds['website'], $salaryData)['status'] === 403, 'Employee cannot change salary');
    expect($admin->post('admin-add-employee.php?id=' . $employeeIds['website'], $salaryData)['status'] === 200, 'Overlapping salary rejected');
    expect((int)scalar('SELECT COUNT(*) FROM employee_salary_history WHERE employee_id=?', [$employeeIds['website']]) === 2, 'Rejected salary does not duplicate history');
    $noBenefits = array_merge($employeeEdit, ['salary' => [['amount' => '17000', 'from' => date('Y-m-d', strtotime('+2 months')), 'to' => '']]]);
    expect($admin->post('admin-add-employee.php?id=' . $employeeIds['website'], $noBenefits)['status'] === 303, 'Salary without benefits saved');
    expect(scalar('SELECT net_salary FROM employee_salary_history WHERE employee_id=? ORDER BY effective_from DESC LIMIT 1', [$employeeIds['website']]) === '17000.00', 'Unchecked benefits deduct zero');
    expect(scalar('SELECT net_salary FROM employee_salary_history WHERE id=?', [$salaryId]) === '13107.50', 'Historical deductions remain unchanged');
    $badDates = array_merge($employeeEdit, ['relieving_date' => date('Y-m-d', strtotime('-1 day'))]);
    expect($admin->post('admin-add-employee.php?id=' . $employeeIds['website'], $badDates)['status'] === 200, 'Invalid relieving date rejected');
    $clientData = ['client_name' => 'Shared Client Updated', 'website_url' => 'https://example.com/new', 'phone' => '9555511111', 'starting_date' => '2026-10-01', 'ending_date' => '2027-09-30', 'package' => 'PRIVATE-PACKAGE-TEST', 'social_links'=>[['platform'=>'Instagram','url'=>'https://instagram.com/example'],['platform'=>'Pinterest','url'=>'https://pinterest.com/example']], 'gmb_url' => 'https://maps.google.com/', 'monthly_reels' => '8', 'monthly_posters' => '12', 'monthly_carousels' => '4', 'payment_total' => '10000', 'payment_request_key' => bin2hex(random_bytes(16)), 'payments' => [['date' => '2026-10-10', 'amount' => '2000']]];
    $admin->request('admin-add-client.php?id=' . $clientId);
    expect($admin->post('admin-add-client.php?id=' . $clientId, $clientData)['status'] === 303, 'Client payment and monthly quantities saved');
    expect(scalar('SELECT remaining_amount FROM clients WHERE id=?', [$clientId]) === '8000.00', '10000 minus 2000 leaves 8000 in database');
    expect((int)scalar('SELECT monthly_carousels FROM clients WHERE id=?', [$clientId]) === 4, 'Monthly carousel quota persisted');
    expect(str_contains($admin->request('add-client.php')['body'], '2026-10-10'), 'Admin sees dated payment history');
    expect(str_contains($admin->request('add-client.php')['body'], 'Pinterest') && str_contains($admin->request('add-client.php')['body'], 'https://instagram.com/example'), 'Client detail dialog includes named social links');
    $employeeClients = $website->request('add-client.php')['body'];
    expect(!str_contains($employeeClients, 'Remaining') && !str_contains($employeeClients, '8,000.00'), 'Employee does not see client remaining balance');
    expect(!str_contains($employeeClients, 'PRIVATE-PACKAGE-TEST') && !str_contains($employeeClients, 'Total payment') && !str_contains($employeeClients, 'Paid') && !str_contains($employeeClients, '2026-10-10'), 'Package and payment ledger hidden from employee');
    expect($website->request('admin-add-client.php?id=' . $clientId)['status'] === 403, 'Employee cannot access client financial form');
    expect($admin->post('admin-add-client.php?id=' . $clientId, $clientData)['status'] === 303, 'Repeated payment request is idempotent');
    expect((int)scalar('SELECT COUNT(*) FROM client_payments WHERE client_id=?', [$clientId]) === 1, 'Repeated request does not duplicate payment');
    $secondPayment = array_merge($clientData, ['payment_request_key' => bin2hex(random_bytes(16)), 'payments' => [['date' => '2026-10-12', 'amount' => '3000.25'], ['date' => '2026-10-13', 'amount' => '999.75']]]);
    expect($admin->post('admin-add-client.php?id=' . $clientId, $secondPayment)['status'] === 303, 'Multiple dated payments saved');
    expect(scalar('SELECT remaining_amount FROM clients WHERE id=?', [$clientId]) === '4000.00', 'Decimal payments subtract exactly');
    $overpay = array_merge($clientData, ['payment_request_key' => bin2hex(random_bytes(16)), 'payments' => [['date' => '2026-10-15', 'amount' => '5000']]]);
    expect($admin->post('admin-add-client.php?id=' . $clientId, $overpay)['status'] === 200, 'Overpayment rejected');
    expect((int)scalar('SELECT COUNT(*) FROM client_payments WHERE client_id=?', [$clientId]) === 3 && scalar('SELECT remaining_amount FROM clients WHERE id=?', [$clientId]) === '4000.00', 'Overpayment transaction rolls back');
    $paymentToEdit=(int)scalar('SELECT id FROM client_payments WHERE client_id=? ORDER BY id LIMIT 1',[$clientId]);
    expect(str_contains($admin->request('admin-add-client.php?id='.$clientId.'&edit_payment='.$paymentToEdit)['body'],'name="action" value="update_payment"'), 'Saved payment edit form is available');
    expect($admin->post('admin-add-client.php?id='.$clientId.'&edit_payment='.$paymentToEdit,['action'=>'update_payment','payment_id'=>$paymentToEdit,'payment_date'=>'2026-10-11','amount'=>'8000'])['status']===200, 'Payment edit cannot exceed agreed total');
    expect(scalar('SELECT amount FROM client_payments WHERE id=?',[$paymentToEdit])==='2000.00', 'Rejected payment edit leaves ledger unchanged');
    expect($admin->post('admin-add-client.php?id='.$clientId,['action'=>'update_payment','payment_id'=>$paymentToEdit,'payment_date'=>'2026-10-11','amount'=>'2100'])['status']===303, 'Saved payment date and amount can be edited');
    expect(scalar('SELECT payment_date FROM client_payments WHERE id=?',[$paymentToEdit])==='2026-10-11' && scalar('SELECT amount FROM client_payments WHERE id=?',[$paymentToEdit])==='2100.00', 'Saved payment changes persist');
    expect(scalar('SELECT remaining_amount FROM clients WHERE id=?',[$clientId])==='3900.00', 'Editing payment refreshes client balance');
    $badAmount = array_merge($clientData, ['payment_request_key' => bin2hex(random_bytes(16)), 'payments' => [['date' => '2026-10-15', 'amount' => '-1']]]);
    expect($admin->post('admin-add-client.php?id=' . $clientId, $badAmount)['status'] === 200, 'Negative payment rejected');
    expect($admin->request('admin-add-client.php?id=' . $clientId, ['csrf' => 'wrong'])['status'] === 419, 'Client payment CSRF enforced');
    if ($browserPath = getenv('BHAVI_BROWSER')) {
        $browserLog = tempnam(sys_get_temp_dir(), 'bhavi_browser_');
        $temporary[] = $browserLog;
        $browserProcess = proc_open([getenv('BHAVI_NODE') ?: 'node', __DIR__ . '/browser-smoke.cjs', $browserPath, $base, $password], [0 => ['pipe', 'r'], 1 => ['file', $browserLog, 'a'], 2 => ['file', $browserLog, 'a']], $browserPipes, dirname(__DIR__));
        if (!is_resource($browserProcess)) throw new RuntimeException('Unable to start browser checks.');
        fclose($browserPipes[0]);
        $browserExit = proc_close($browserProcess);
        $browserOutput = file_get_contents($browserLog);
        expect($browserExit === 0 && str_contains($browserOutput, 'PASS: Browser'), 'Interactive browser checks: ' . $browserOutput);
        echo $browserOutput;
    }
    foreach ($routes as $route) if (!in_array($route, ['manager-review-work.php', 'download-asset.php'], true) && !str_contains($route, 'employee-dashboard') && !in_array($route, ['apply-leaves.php', 'check-leave.php', 'admin-dashboard.php'], true)) expect($manager->request($route)['status'] === 200, 'Manager page ' . $route);
    $manager->request('manager-dailywork.php');
    $historicSheet = (int)scalar('SELECT id FROM daily_work_submissions WHERE employee_id=? AND work_date=?', [$employeeIds['website'], $yesterday]);
    expect($manager->post('manager-dailywork.php', ['action' => 'delete_submission', 'id' => $historicSheet])['status'] === 303, 'Manager deletes work report');
    expect((int)scalar('SELECT COUNT(*) FROM daily_work_entries WHERE submission_id=?', [$historicSheet]) === 0, 'Deleted report rows removed');
    expect($manager->request('manager-assign-work.php?edit=' . $assignmentId)['status'] === 403, 'Manager cannot edit assignments');
    $manager->request('manager-assign-work.php');
    expect($manager->post('manager-assign-work.php', ['action' => 'delete_assignment', 'id' => $assignmentId])['status'] === 403, 'Manager cannot delete assignments');
    expect((int)scalar('SELECT COUNT(*) FROM work_assignments WHERE id=? AND deleted_at IS NULL', [$assignmentId]) === 1, 'Unauthorized assignment deletion is blocked');
    $admin->request('manager-assign-work.php');
    expect($admin->post('manager-assign-work.php', ['action' => 'delete_assignment', 'id' => $assignmentId])['status'] === 303, 'Admin can delete assignments');
    expect(!str_contains($website->request($dashboards['website'])['body'], 'Responsive page with contact form'), 'Deleted task is no longer assigned');
    $admin->request('admin-holidays.php');
    expect($admin->post('admin-holidays.php', ['action' => 'delete_holiday', 'id' => $holidayId])['status'] === 303, 'Holiday delete');
    expect((int)scalar('SELECT is_published FROM holidays WHERE id=?', [$holidayId]) === 0, 'Deleted holiday hidden');
    $admin->request('add-client.php');
    expect($admin->post('add-client.php', ['action' => 'delete_client', 'id' => $clientId])['status'] === 303, 'Client delete');
    expect(!str_contains($website->request('add-client.php')['body'], 'Shared Client Updated'), 'Deleted client hidden from employee');
    $admin->request('admin-employees.php');
    expect($admin->post('admin-employees.php', ['action' => 'delete_employee', 'id' => $employeeIds['social_media']])['status'] === 303, 'Employee account deletion');
    expect($browsers['social_media']->request($dashboards['social_media'])['headers']['location'] === 'login.php', 'Deleted employee session loses access');
    expect(str_contains($manager->request('manager-dashboard.php')['body'], '<strong>4</strong>'), 'Employee dashboard total updates after deletion');
    $website->request('change-password.php');
    $newPassword = '  New-Password-Test!  ';
    expect($website->post('change-password.php', ['current_password' => $password, 'new_password' => $newPassword, 'confirm_password' => $newPassword])['status'] === 303, 'Employee changes password');
    expect(password_verify($newPassword, (string)scalar('SELECT password_hash FROM users WHERE id=?', [$employeeIds['website']])), 'Password whitespace is preserved');
    $website->request($dashboards['website']);
    expect($website->request('logout.php')['status'] === 405, 'Logout requires POST');
    expect($website->post('logout.php', [])['headers']['location'] === 'login.php', 'Logout works');
    expect($website->request($dashboards['website'])['headers']['location'] === 'login.php', 'Protected route after logout');
    $website->login('website.test', $newPassword, $dashboards['website']);
    echo "PASS: $checks integration checks (authentication, roles, departments, CRUD, assignments, submissions, reports, Excel, documents, department changes, notifications, reviews, leaves and logout).\n";
} catch (Throwable $e) {
    fwrite(STDERR, 'FAIL: ' . $e->getMessage() . "\n");
    if (isset($log) && is_file($log)) fwrite(STDERR, substr(file_get_contents($log), -3500));
    $failed = true;
} finally {
    if (is_resource($process)) {
        proc_terminate($process);
        proc_close($process);
    }
    // Only drop the test database created by this process.
    if (preg_match('/^bhavi_portal_test_[a-f0-9]{12}$/D', $database)) $pdo->exec("DROP DATABASE IF EXISTS `$database`");
    foreach ($temporary as $file) if (is_file($file)) unlink($file);
}
exit(isset($failed) ? 1 : 0);
