<?php
require_once __DIR__ . '/layout.php';
$user=require_roles([$expectedRole]);
if (($_GET['view']??'')==='team') redirect('admin-employees.php');
if (($_GET['view']??'')==='work') redirect('manager-dailywork.php');
$employeeCount=count_value("SELECT COUNT(*) FROM users WHERE role='employee' AND deleted_at IS NULL");
$submittedCount=count_value("SELECT COUNT(*) FROM daily_work_submissions s WHERE s.work_date=? AND s.submission_status='submitted' AND EXISTS (SELECT 1 FROM daily_work_entries e WHERE e.submission_id=s.id)",[today()]);
$leaveCount=count_value("SELECT COUNT(*) FROM leave_requests WHERE status='pending'");
$clientCount=count_value('SELECT COUNT(*) FROM clients WHERE is_active=1 AND deleted_at IS NULL');
$holidayCount=count_value('SELECT COUNT(*) FROM holidays WHERE is_published=1 AND holiday_date>=?',[today()]);
$departmentTotals=rows("SELECT d.id,d.name,COUNT(u.id) AS total,COALESCE(SUM(s.submission_status='submitted' AND EXISTS (SELECT 1 FROM daily_work_entries e WHERE e.submission_id=s.id)),0) AS submitted FROM departments d LEFT JOIN employee_profiles ep ON ep.department_id=d.id LEFT JOIN users u ON u.id=ep.user_id AND u.role='employee' AND u.account_status='active' AND u.deleted_at IS NULL LEFT JOIN daily_work_submissions s ON s.employee_id=u.id AND s.work_date=? WHERE d.is_active=1 GROUP BY d.id,d.name ORDER BY d.name",[today()]);
$pending=rows("SELECT u.full_name,d.name AS department_name FROM users u JOIN employee_profiles ep ON ep.user_id=u.id JOIN departments d ON d.id=ep.department_id WHERE u.role='employee' AND u.account_status='active' AND u.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM daily_work_submissions s WHERE s.employee_id=u.id AND s.work_date=? AND s.submission_status='submitted' AND EXISTS (SELECT 1 FROM daily_work_entries e WHERE e.submission_id=s.id)) ORDER BY u.full_name",[today()]);
$notifications=rows('SELECT title,message FROM notifications WHERE recipient_id=? ORDER BY created_at DESC,id DESC LIMIT 5',[$user['id']]);
page_start(ucfirst($user['role']).' dashboard',dashboard_path($user));
?><p class="muted">Welcome, <?= h($user['full_name']) ?>. Your team's latest work, requests and records are here.</p><div class="stats-grid"><a class="stat-card" href="admin-employees.php"><h2>Total employees</h2><strong><?= $employeeCount ?></strong><p>View your employee directory</p></a><a class="stat-card" href="manager-dailywork.php?from_date=<?= today() ?>&amp;to_date=<?= today() ?>"><h2>Work submitted today</h2><strong><?= $submittedCount ?></strong><p>View all department updates</p></a><a class="stat-card" href="manager-leave-requist.php?status=pending"><h2>Leave requests</h2><strong><?= $leaveCount ?></strong><p>Awaiting your decision</p></a><a class="stat-card" href="admin-holidays.php"><h2>Upcoming holidays</h2><strong><?= $holidayCount ?></strong><p>Shared with the whole team</p></a></div>
<div class="two-columns"><section class="panel"><div class="panel-heading"><h2>Today by department</h2><a href="manager-dailywork.php">View reports</a></div><?php foreach ($departmentTotals as $department): $percent=$department['total']?min(100,round(100*$department['submitted']/$department['total'])):0; ?><div class="progress-row"><div class="progress-label"><a href="manager-dailywork.php?department=<?= $department['id'] ?>"><?= h($department['name']) ?></a><span><?= $department['submitted'] ?> / <?= $department['total'] ?> submitted</span></div><div class="progress-track" role="progressbar" aria-label="<?= h($department['name']) ?> submissions" aria-valuenow="<?= $percent ?>" aria-valuemin="0" aria-valuemax="100"><span style="width:<?= $percent ?>%"></span></div></div><?php endforeach; ?><a class="button" href="manager-assign-work.php">+ Assign work</a></section><section class="panel"><div class="panel-heading"><h2>Latest updates</h2><a href="manager-notification.php">View all</a></div><?php if (!$notifications): ?><p class="muted">Team notifications will appear here.</p><?php endif; foreach ($notifications as $notification): ?><article style="margin-bottom:18px"><h3><?= h($notification['title']) ?></h3><p class="muted"><?= h($notification['message']) ?></p></article><?php endforeach; ?></section></div>
<section class="panel"><div class="panel-heading"><h2>Pending daily submissions · <?= count($pending) ?></h2><a href="add-client.php"><?= $clientCount ?> clients</a></div><?php if (!$pending): ?><p class="muted">All active employees have submitted, or no employees have been added yet.</p><?php else: ?><div class="table-scroll"><table><thead><tr><th>Employee</th><th>Department</th></tr></thead><tbody><?php foreach ($pending as $employee): ?><tr><td><?= h($employee['full_name']) ?></td><td><?= h($employee['department_name']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section><?php page_end(); ?>
